services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notification_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"   # management UI

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"     # SMTP
      - "8025:8025"     # web UI

volumes:
  postgres_data: